[package]
name = "cxstor/set"
description = "A Luau function that converts a list into a set."
version = "1.1.2"
liscense = "MIT"
authors = ["Cxstor <cxstor@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["README.md", "wally.zip", ".gitignore"]

[dependencies]

[server-dependencies]

[dev-dependencies]